global:
  scrape_interval: 15s
scrape_configs:
- job_name: auto_observability-postgres-2_postgres
  scrape_interval: 15s
  scrape_timeout: 10s
  file_sd_configs:
  - files:
    - targets/auto_observability-postgres-2_postgres.yml
